## general app info ##
app:
  version: @project.version@
  description: @project.description@
  source.url: https://github.com/felipeguilhermefs/diff

spring.threads.virtual.enabled: true


spring.docker.compose.file: compose-local.yaml

## open api ##
# springdoc default is not json for some reason, spring is (go figure)
springdoc.default-produces-media-type: application/json

## cache ##
# 10 minutes should be enough for a diff use case
diff.cache.ttl-minutes: 10
